from src.linear_regression_dashboard.plots.time_series_plot import TwoLinesPlot
from src.linear_regression_dashboard.plots.scatter_plot import AdjustableScatterPlot
from src.linear_regression_dashboard.plots.squared_sum_errors_plot import SSEPlot
